environment:
  build_version: 1.0.1

version: $(build_version)-{build}

pull_requests:
  do_not_increment_build_number: true
  
configuration: Release

image: Visual Studio 2017

install:
- dotnet tool install -g InheritDocTool

before_build:
- ps: . .\patch-version.ps1 src\trybot.extensions.http.csproj $($env:build_version)

build_script:
- msbuild /t:Restore /p:Configuration=%CONFIGURATION% trybot.extensions.http.sln
- msbuild /t:Build /p:Configuration=%CONFIGURATION% trybot.extensions.http.sln
  
after_build:
- inheritdoc -o
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%CONFIGURATION% /p:PackageOutputPath=..\artifacts src\trybot.extensions.http.csproj

test_script:
- dotnet test test\trybot.extensions.http.tests.csproj -f netcoreapp2.1 -c %CONFIGURATION% --no-build
  
artifacts:
- path: artifacts\Trybot.*.nupkg
  name: NuGet

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true